repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.10
    hooks:
      # Run the linter (fix issues automatically).
      - id: ruff-check
        args: [--fix]
        pass_filenames: true
        stages: [commit]

      # Run the formatter.
      - id: ruff-format
        pass_filenames: true
        stages: [commit]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-yaml
      - id: check-case-conflict
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/kynan/nbstripout
    rev: 0.8.1
    hooks:
      - id: nbstripout
        pass_filenames: true
        stages: [commit]
