# SPDX-FileCopyrightText: : 2022 The PyPSA-China Authors
#
# SPDX-License-Identifier: MIT

name: pypsa-china
channels:
  - conda-forge
  - bioconda
dependencies:
  - python>=3.12
  - pip

  - pypsa>=0.31
  - atlite>=0.2.6
  - dask
  - snakemake-storage-plugin-http
  # - pyasyncore
  # - pyasynchat

  # Dependencies of the workflow itself
  - xlrd
  - rioxarray
  - openpyxl
  - pycountry
  - seaborn
  - snakemake-minimal>=8.0
  - memory_profiler
  - yaml
  - pytables
  - lxml
  - powerplantmatching>=0.4.8
  - numpy
  - pandas
  - geopandas
  - xarray
  - netcdf4
  - networkx
  - scipy
  - shapely
  - progressbar2
  - pyomo
  - matplotlib
  - proj
  - fiona
  - geopy
  - tqdm
  - pytz
  - country_converter
  - tabula-py

  # Keep in conda environment when calling ipython
  - ipython

  # GIS dependencies:
  - cartopy
  - descartes
  - rasterio

  - pip:
    - vresutils>=0.3.1
    - tsam>=1.1.0
    - gurobipy==11.0.3
